simulator:
  readings:
    file: './sensor.csv'
  device_id: '207278c4-836a-443a-98ba-f5ca914e5ed3'  # TODO: adjust with actual UUID in your app
rabbitMQ:
  queue: test_queue
  exchange: test_exchange
  url: 'amqps://ivpbhbrx:BB9NSs5i3qYczwRO-ofc-a9WkXEh04r7@sparrow.rmq.cloudamqp.com/ivpbhbrx'