simulator:
  readings:
    file: './sensor.csv'
  device_id: '14840429-1f8f-4cf5-a96e-4a526a9ca216'  # TODO: adjust with actual UUID in your app
rabbitMQ:
  queue: test_queue
  exchange: test_exchange
  url: 'amqps://ivpbhbrx:BB9NSs5i3qYczwRO-ofc-a9WkXEh04r7@sparrow.rmq.cloudamqp.com/ivpbhbrx'