simulator:
  readings:
    file: './sensor.csv'
  device_id: '48a553a3-3409-4c37-a197-3d72118d52f3'  # TODO: adjust with actual UUID in your app; change last digit to 3
rabbitMQ:
  queue: test_queue
  exchange: test_exchange
  url: 'amqps://ivpbhbrx:BB9NSs5i3qYczwRO-ofc-a9WkXEh04r7@sparrow.rmq.cloudamqp.com/ivpbhbrx'