simulator:
  readings:
    file: './sensor.csv'
  device_id: 'f4331690-b3dc-4c05-a2f7-94d2e8b0793f'  # TODO: adjust with actual UUID in your app; change last digit to 3
rabbitMQ:
  queue: test_queue
  exchange: test_exchange
  url: 'amqps://ivpbhbrx:BB9NSs5i3qYczwRO-ofc-a9WkXEh04r7@sparrow.rmq.cloudamqp.com/ivpbhbrx'