simulator:
  readings:
    file: './sensor.csv'
  device_id: 'ddd8a30a-3e59-4d39-b225-282f4e9001c3'  # TODO: adjust with actual UUID in your app; change last digit to 3
rabbitMQ:
  queue: test_queue
  exchange: test_exchange
  url: 'amqps://ivpbhbrx:BB9NSs5i3qYczwRO-ofc-a9WkXEh04r7@sparrow.rmq.cloudamqp.com/ivpbhbrx'