#FROM maven:3.8.3-openjdk-17 AS builder
#COPY ./src/ /root/src
#COPY ./pom.xml /root/
##COPY ./checkstyle.xml /root/
#WORKDIR /root
#RUN mvn package
#RUN java -Djarmode=layertools -jar /root/target/energy-mgmt-login-0.0.1-SNAPSHOT.jar list
#RUN java -Djarmode=layertools -jar /root/target/energy-mgmt-login-0.0.1-SNAPSHOT.jar extract
#RUN ls -l /root
#FROM openjdk:17-jdk-slim-buster
#ENV TZ=UTC
#ENV DB_IP=localhost
#ENV DB_PORT=5432
#ENV DB_USER=login_user
#ENV DB_PASSWORD=auth
#ENV DB_DBNAME=user-db
#COPY --from=builder /root/dependencies/ ./
#COPY --from=builder /root/snapshot-dependencies/ ./
#RUN sleep 10
#COPY --from=builder /root/spring-boot-loader/ ./
#COPY --from=builder /root/application/ ./
#ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher","-XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms512m -Xmx512m -XX:+UseG1GC -XX:+UseSerialGC -Xss512k -XX:MaxRAM=72m"]

# Start with a base image that includes Java
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the jar file from target directory into the container
COPY target/energy-mgmt-login-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 6582

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
