database:
  user: ${DB_USER:vladbarto}
  name: ${DB_DBNAME:user-db}
  port: ${DB_PORT:5432}
  ip: ${DB_IP:localhost}
  password: ${DB_PASSWORD:1234}
spring:
  application:
    name: energy-mgmt-user
  datasource:
    url: jdbc:postgresql://${database.ip}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 6584
  servlet:
    context-path: '/api-user'
  error:
    whitelabel:
      enabled: false