spring:
  application:
    name: energy-mgmt-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/city-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 6584
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false