database:
  user: ${DB_USER:login_user}
  name: ${DB_DBNAME:user-db}
  port: ${DB_PORT:5432}
  ip: ${DB_IP:localhost}
  password: ${DB_PASSWORD:auth}
api:
  userService:
    host: ${BACKEND_USER_HOST:localhost}
    port: ${BACKEND_USER_PORT:6584}
  deviceService:
    host: ${BACKEND_DEVICE_HOST:localhost}
    port: ${BACKEND_DEVICE_PORT:6585}
spring:
  application:
    name: energy-mgmt-login
  datasource:
    url: jdbc:postgresql://${database.ip}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 6582
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false
security:
  secret-key: PS-SD-2024-3023X-1q2w3e4r5t6y7u8i9o0p
  token-expiration-days: 15
microservices:
#  userService: "http://localhost:6584/api"
#  deviceService: "http://localhost:6585/api"
#  userService: "http://host.docker.internal:6584/api"
#  deviceService: "http://host.docker.internal:6585/api"
  userService: http://${api.userService.host}:${api.userService.port}/api
  deviceService: http://${api.deviceService.host}:${api.deviceService.port}/api